#!/bin/sh

source "$HOME/.config/design/colors.sh"
source "$HOME/.config/design/icons.sh"

export ITEM_DIR="$HOME/.config/sketchybar/items"
export PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

export SYMBOLS_FONT="Symbols Nerd Font"
export FONT="CaskaydiaCove Nerd Font"

# VARIABLES
# ---------------------------------------------
blur_radius=30


# BAR
# ---------------------------------------------
bar_properties=(
  position=top
  height=30
  color=$COLOR_TRANSPARENT
  y_offset=5
  padding_left=10
  padding_right=10
)

sketchybar --bar "${bar_properties[@]}"


# DEFAULTS
# ---------------------------------------------
default=(
  padding_left=6
  padding_right=6

  background.border_color=$COLOR_YELLOW
  background.corner_radius=12
  background.border_width=2
  background.height=30

  icon.color=$COLOR_YELLOW
  icon.highlight_color=$COLOR_BACKGROUND
  icon.padding_left=6
  icon.padding_right=2
  icon.font="$FONT:Regular:16.0"

  label.color=$COLOR_YELLOW
  label.color=$COLOR_BACKGROUND
  label.padding_left=4
  label.padding_right=8
  label.font="$FONT:Regular:12.0"
)

# Right side defaults (only show on display 1)
right_display=(
  associated_display=1
)

sketchybar --default "${default[@]}"


#--- LEFT ---

# Spaces  
source "$ITEM_DIR/spaces.sh"

# Separator
source "$ITEM_DIR/separator.sh" "separator.l2" "left" 4 4

# Front App
source "$ITEM_DIR/front_app.sh"

#-------------------------------------





#--- CENTER ---

# Spotify
source "$ITEM_DIR/spotify.sh"

#-------------------------------------




#--- RIGHT ---

# Clock
source "$ITEM_DIR/clock.sh"
sketchybar --set time "${right_display[@]}" \
           --set date "${right_display[@]}"

# Separator
source "$ITEM_DIR/separator.sh" "separator.r1" "right" 4 4
sketchybar --set separator.r1 "${right_display[@]}"

# Status items (ip_address, volume, battery)
source "$ITEM_DIR/status.sh"
sketchybar --set ip_address "${right_display[@]}" \
           --set volume "${right_display[@]}" \
           --set battery "${right_display[@]}"

# Separator
source "$ITEM_DIR/separator.sh" "separator.r2" "right" 4 4
sketchybar --set separator.r2 "${right_display[@]}"

# Activity items (ram, disk, cpu)
source "$ITEM_DIR/activity.sh"
sketchybar --set ram "${right_display[@]}" \
           --set disk "${right_display[@]}" \
           --set cpu "${right_display[@]}"

#-------------------------------------




##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update

sketchybar --hotload true