#!/bin/sh

source "$HOME/.config/design/colors.sh"
source "$HOME/.config/design/icons.sh"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"


# VARIABLES
# ---------------------------------------------
blur_radius=30


# BAR
# ---------------------------------------------
bar_properties=(
  position=top
  height=30
  color=$COLOR_TRANSPARENT
  y_offset=5
  padding_left=5
  padding_right=15
)

sketchybar --bar "${bar_properties[@]}"


# DEFAULTS
# ---------------------------------------------
default=(
  padding_left=8
  padding_right=8

  background.color=$COLOR_YELLOW
  background.corner_radius=12
  background.border_width=2
  background.height=30

  icon.color=$COLOR_YELLOW
  icon.highlight_color=$COLOR_BACKGROUND
  icon.padding_left=6
  icon.padding_right=2
  icon.font="CaskaydiaCove Nerd Font:Regular:16.0"

  label.color=$COLOR_YELLOW
  label.color=$COLOR_BACKGROUND
  label.padding_left=4
  label.padding_right=8
  label.font="CaskaydiaCove Nerd Font:Regular:12.0"
)
sketchybar --default "${default[@]}"



# SPACE 
# ------------------------------------------------
sketchybar --add event window_change

COLORS_SPACE=($COLOR_YELLOW $COLOR_CYAN $COLOR_MAGENTA $COLOR_WHITE $COLOR_BLUE $COLOR_RED $COLOR_GREEN $COLOR_BROWN $COLOR_YELLOW $COLOR_CYAN $COLOR_MAGENTA $COLOR_YELLOW $COLOR_CYAN $COLOR_MAGENTA)
LENGTH=${#ICONS_SPACE[@]}

for i in "${!ICONS_SPACE[@]}"
do
  sid=$(($i+1))
  PAD_LEFT=2
  PAD_RIGHT=2
  if [[ $i == 0 ]]; then
    PAD_LEFT=8
  elif [[ $i == $(($LENGTH-1)) ]]; then
    PAD_RIGHT=8
  fi
  sketchybar --add space space.$sid left                                       \
             --set       space.$sid script="$PLUGIN_DIR/app_space.sh"          \
                                    associated_space=$sid                      \
                                    padding_left=$PAD_LEFT                     \
                                    padding_right=$PAD_RIGHT                   \
                                    background.color=${COLORS_SPACE[i]}        \
                                    background.border_width=0                  \
                                    background.corner_radius=6                 \
                                    background.height=24                       \
                                    label.font="Symbols Nerd Font:Regular:16.0" \
                                    icon.font="CaskaydiaCove Nerd Font:Regular:12.0" \
                                    icon=${ICONS_SPACE[i]}                     \
                                    icon.color=${COLORS_SPACE[i]}              \
                                    label="_"                                  \
                                    label.color=${COLORS_SPACE[i]}             \
             --subscribe space.$sid front_app_switched window_change
done

sketchybar --add bracket spaces '/space\..*/'                      \
           --set         spaces background.color=$COLOR_BACKGROUND

sketchybar --add item seperator.l2 left                   \
           --set      seperator.l2 padding_left=4         \
                                   padding_right=4        \
                                   background.drawing=off \
                                   icon.drawing=off       \
                                   label.drawing=off


##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item time right                        \
           --set      time script="$PLUGIN_DIR/time.sh" \
                           update_freq=5                \
                           padding_left=2               \
                           padding_right=6              \
                           background.color=$COLOR_WHITE  \
                           background.border_width=0    \
                           background.corner_radius=8   \
                           background.height=20         \
                           icon=$ICON_CLOCK             \
                           icon.highlight=on            \
                           label.highlight=on           \
           --add item date right                        \
           --set      date script="$PLUGIN_DIR/date.sh" \
                           update_freq=60               \
                           padding_left=6               \
                           padding_right=2              \
                           background.color=$COLOR_WHITE  \
                           background.border_width=0    \
                           background.height=20         \
                           background.corner_radius=8   \
                           icon=$ICON_CALENDAR          \
                           icon.highlight=on            \
                           label.highlight=on           \

sketchybar --add bracket clock time date                          \
           --set         clock background.color=$COLOR_BACKGROUND \
                               background.border_color=$COLOR_WHITE


sketchybar --add item seperator.r1 right                  \
           --set      seperator.r1 padding_left=4         \
                                   padding_right=4        \
                                   background.drawing=off \
                                   icon.drawing=off       \
                                   label.drawing=off

sketchybar --add item  ip_address right                              \
           --set       ip_address script="$PLUGIN_DIR/ip_address.sh" \
                                  update_freq=30                     \
                                  padding_left=2                     \
                                  padding_right=6                    \
                                  background.border_width=0    \
                                  background.height=20         \
                                  background.corner_radius=8   \
                                  icon.highlight=on                  \
                                  label.highlight=on                 \
           --subscribe ip_address wifi_change                        \
                                                                     \
           --add item  volume right                                  \
           --set       volume script="$PLUGIN_DIR/volume.sh"         \
                              padding_left=2                         \
                              padding_right=2                        \
                              background.border_width=0    \
                              background.color=$COLOR_BLUE    \
                              background.height=20         \
                              background.corner_radius=8   \
                              icon.highlight=on                  \
                              label.highlight=on                 \
           --subscribe volume volume_change                          \
                                                                     \
           --add item  battery right                                 \
           --set       battery script="$PLUGIN_DIR/battery.sh"       \
                               update_freq=120                       \
                               padding_left=6                        \
                               padding_right=2                      \
                               background.color=$COLOR_BLUE    \
                               background.border_width=0    \
                               background.height=20         \
                               background.corner_radius=8   \
                               icon.highlight=on                  \
                               label.highlight=on                 \
           --subscribe battery system_woke power_source_change

sketchybar --add bracket status ip_address volume battery           \
           --set         status background.color=$COLOR_BACKGROUND  \
                                background.border_color=$COLOR_BLUE

sketchybar --add item seperator.r2 right                  \
           --set      seperator.r2 padding_left=4         \
                                   padding_right=4        \
                                   background.drawing=off \
                                   icon.drawing=off       \
                                   label.drawing=off      
                              
sketchybar --add item ram right                         \
           --set      ram script="$PLUGIN_DIR/ram.sh"   \
                          update_freq=60                \
                          padding_left=2                \
                          padding_right=6               \
                          background.border_width=0     \
                          background.color=$COLOR_CYAN    \
                          background.height=20          \
                          icon=$ICON_RAM                \
                          icon.highlight=on                  \
                          label.highlight=on                 \
                                                        \
           --add item disk right                        \
           --set      disk script="$PLUGIN_DIR/disk.sh" \
                           update_freq=60               \
                           padding_left=2               \
                           padding_right=2              \
                           background.border_width=0    \
                           background.color=$COLOR_CYAN    \
                           background.height=20         \
                           icon=$ICON_DISK              \
                           icon.highlight=on                  \
                           label.highlight=on                 \
                                                        \
           --add item cpu right                         \
           --set      cpu script="$PLUGIN_DIR/cpu.sh"   \
                          update_freq=60                \
                          padding_left=6                \
                          padding_right=2               \
                          background.border_width=0     \
                          background.color=$COLOR_CYAN    \
                          background.height=20          \
                          icon=$ICON_CPU                \
                          icon.highlight=on                  \
                          label.highlight=on                 \

sketchybar --add bracket activity ram disk cpu                      \
           --set         activity background.color=$COLOR_BACKGROUND     \
                                  background.border_color=$COLOR_CYAN


##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
