#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

osascript -e 'tell application id "tracesOf.Uebersicht" to refresh'

yabai -m space 1 --label ios
yabai -m space 2 --label and
yabai -m space 3 --label web
yabai -m space 4 --label bkd
yabai -m space 5 --label fun
yabai -m space 6 --label 6
yabai -m space 7 --label 7
yabai -m space 8 --label 8

# rules for apps
yabai -m rule --add app="^Xcode$" display=1 space=1
yabai -m rule --add app="^Simulator$" display=3 space=14 manage=off
yabai -m rule --add app="^CleanShot X$" sticky=on manage=off opacity=1.0
yabai -m rule --add app="^Kando$" manage=off opacity=1.0

yabai -m rule --add app="^(Keyboard Maestro|Dropover|Alfred Preferences|Karabiner-Elements|Karabiner-EventViewer|VLC|Steam|App Store|Activity Monitor|Disk Utility|Archive Utility|Finder|Raycast|1Password|Notes)$" manage=off opacity=1.0
yabai -m signal --add label=unmanagedAndCenteredApps event=window_created app='^(Keyboard Maestro|Dropover|Alfred Preferences|Karabiner-Elements|Karabiner-EventViewer|VLC|Steam|App Store|Activity Monitor|Disk Utility|Archive Utility|Finder|Raycast|1Password|Notes)$' action='window="$(yabai -m query --windows --window)"; display="$(/opt/homebrew/bin/yabai -m query --displays --window)"; coords="$(/opt/homebrew/bin/jq --argjson window "$window" --argjson display "$display" -nr "((\$display.frame | .x + .w / 2) - (\$window.frame.w / 2) | tostring) + \":\" + ((\$display.frame | .y + .h / 2) - (\$window.frame.h / 2) | tostring)")"; /opt/homebrew/bin/yabai -m window --move "abs:$coords"'

yabai -m rule --add app="^Spotify$" display=3 space=13
yabai -m rule --add app='^Slack$' display=2 space=10
yabai -m rule --add app="^System Settings$" scratchpad="System Settings" grid="22:22:4:4:20:20"
yabai -m rule --add app="^Obsidian$" scratchpad="Obsidian" grid="22:22:1:1:20:20" sticky=on
yabai -m rule --add app="^Reader$" scratchpad="Reader" grid="22:22:1:1:20:20" sticky=on

yabai -m rule --apply

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_topmost               off
yabai -m config window_placement             second_child
yabai -m config window_opacity               off
yabai -m config window_shadow                float
yabai -m config window_border                off
yabai -m config window_border_width          1
yabai -m config active_window_border_color   0xff87875F
yabai -m config normal_window_border_color   0xff444444
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.80
yabai -m config split_ratio                  0.66
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  35
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   10


# Signals
#yabai -m signal --add event=space_changed action='yabai -m window --focus $(yabai -m query --windows --space | jq -r '\''[.[]|select(."is-visible")][-1].id'\'')'
