#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

#osascript -e 'tell application id "tracesOf.Uebersicht" to refresh'

yabai -m space 1 
yabai -m space 2 
yabai -m space 3
yabai -m space 4
yabai -m space 5
yabai -m space 6
yabai -m space 7
yabai -m space 8

# rules for apps
yabai -m rule --add app="^CleanShot X$" sticky=on manage=off opacity=1.0
yabai -m rule --add app="^Kando$" manage=off opacity=1.0
yabai -m rule --add app="^ForkLift$" manage=off opacity=1.0

yabai -m rule --add app="^(Keyboard Maestro|Dropover|Alfred Preferences|Karabiner-Elements|Karabiner-EventViewer|VLC|Steam|App Store|Activity Monitor|Disk Utility|Archive Utility|Finder|Raycast|1Password|Notes)$" manage=off opacity=1.0
yabai -m signal --add label=unmanagedAndCenteredApps event=window_created app='^(Keyboard Maestro|Dropover|Alfred Preferences|Karabiner-Elements|Karabiner-EventViewer|VLC|Steam|App Store|Activity Monitor|Disk Utility|Archive Utility|Finder|Raycast|1Password|Notes)$' action='window="$(yabai -m query --windows --window)"; display="$(/opt/homebrew/bin/yabai -m query --displays --window)"; coords="$(/opt/homebrew/bin/jq --argjson window "$window" --argjson display "$display" -nr "((\$display.frame | .x + .w / 2) - (\$window.frame.w / 2) | tostring) + \":\" + ((\$display.frame | .y + .h / 2) - (\$window.frame.h / 2) | tostring)")"; /opt/homebrew/bin/yabai -m window --move "abs:$coords"'

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Obsidian$" manage=off
yabai -m rule --add app="^Reader$" manage=off
yabai -m rule --add app="^Spotify$" scratchpad="Spotify" sticky=on
yabai -m rule --add app="^Slack$" scratchpad="Slack" sticky=on

yabai -m rule --apply

yabai -m config                                 \
    external_bar                 off:40:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          on             \
    focus_follows_mouse          on             \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_insertion_point       focused        \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  40             \
    bottom_padding               10             \
    left_padding                 10             \
    right_padding                10             \
    window_gap                   05             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap           

